---
kind: ConfigMap
apiVersion: v1
metadata:
  name: notification-config
  namespace: notification-service
data:
  application.yaml: |-
    server:
      shutdown: graceful
      lifecycle:
        timeout-per-shutdown-phase: 15
      port: 8080
      compression:
        enabled: true
        mime-types: application/json,text/css,application/javascript
        min-response-size: 2048

    wavefront:
      application:
        name: notification-service-k8s
      freemium-account: true

    # Logging
    logging.level.org.springframework: INFO

    # Metrics
    management:
      endpoint:
        health:
          probes:
            enabled: true
      health:
        livenessState:
          enabled: true
        readinessState:
          enabled: true
        restart:
          enabled: true
        metrics:
          enabled: true
        prometheus:
          enabled: true
      endpoints:
        web:
          exposure:
            include: '*'
      metrics:
        export:
          prometheus:
            enabled: true
          wavefront:
            enabled: true

    notification-service-api-id: http://notification-service-api.svc.cluster.local:8080
    registry-service: http://registry-service.svc.cluster.local:8080

      sleuth:
        sampler:
          probability: 1.0
        config:
          # Allow the microservices to override the remote properties with their own System properties or config file
          allow-override: true
          # Override configuration with any local property source
          override-none: true
      messages:
        basename: messages/messages
      cloud:
        kubernetes:
          discovery:
            enabled: true
        loadbalancer:
          ribbon:
            enabled: false
        gateway:
          x-forwarded:  
            enabled: true 
            for-enabled: true 
            proto-enabled: true 
            host-append: false  
            port-append: false  
            proto-append: false
          routes:
            - id: notification-service
              uri: http://notification-service.svc.cluster.local:8080
              predicates:
                - Path=/api/notification-api/**
              filters:
                - StripPrefix=2
            - id: registry-service
              uri: http://registry-service.svc.cluster.local:8080
              predicates:
                - Path=/api/registry/**
              filters:
                - StripPrefix=2
            - id: template-service
              uri: http://template-service.svc.cluster.local:8080
              predicates:
                - Path=/api/template/**
              filters:
                - StripPrefix=2
    vets:
      cache:
        ttl: 60
        heap-size: 101

