---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification-service-api
  name: notification-service-api
  namespace: notification-service
spec:
  ports:
  - name: "http"
    port: 8080
    # appProtocol: "http"
    targetPort: 8080
  selector:
    app: notification-service-api
status:
  loadBalancer: {}
