---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry-service
  name: registry-service
  namespace: notification-service
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app: registry-service
status:
  loadBalancer: {}
