---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: template-service
  name: template-service
  namespace: notification-service  
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app: template-service
status:
  loadBalancer: {}
